version: '3'

services:
  client:
    image: node:18
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:5173
    command: yarn dev

  functions:
    image: node:18
    working_dir: /app
    volumes:
      - ./functions:/app
    ports:
      - 3030:3000
    command: yarn dev
